# Site settings
title: 麦克船长的技术、产品与商业博客
description: "麦克船长对于技术、产品、商业等领域的分享|AI,A.I.,NLP,神经网络,人工智能,自然语言处理,BERT,GPT,ChatGPT,OpenAI,阿里巴巴,P9,运营,淘宝,天猫,总监,高管"
url: "https://www.mikecaptain.com"
ogimage: "img/default-ogimage.png"
author:
  name: "Poechant"
  email: "zhongchao.ustc@gmail.com"
  url: "https://www.mikecaptian.com"


# Build settings
baseurl:  # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/
collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:title/
    directory: _posts

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
version: "1.0.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
