# Site settings
title: Blog - technology and science at TheReviewIndex
description: "A blog for sharing thoughts on technology, science and insights at TheReviewIndex."
url: "http://poechant.github.io"
ogimage: "img/default-ogimage.png"
author:
  name: "Poechant"
  email: "zhongchao.ustc@gmail.com"
  url: "https://github.com/poechant"


# Build settings
baseurl:  # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/
collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:title/
    directory: _posts

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
version: "1.0.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
